### PR TITLE
Update to 2.0-beta6

### PR DESCRIPTION
**Pull request by Leonidas-from-XIV**
This also fixes building on current brew (which ships 4.06 which breaks due to `safe-string`)

### CODE REVIEW

**Comment by dbuenzli** [comment]
Thanks !

**Comment by dbuenzli** [comment]
@Leonidas-from-XIV are you sure about the `4.06` claim ? AFAIK the patches for 4.06 are on master but not in a published release yet.

**Comment by Leonidas-from-XIV** [comment]
Uhh, you are completely right. I misclicked on Github and looked at the list of commits to master since the beta6 release, so it will fail to build if running the non-cold boot branch. Should I send you a PR that temporarily disables using the system OCaml until beta7 comes out?

**Comment by dbuenzli** [comment]
> Should I send you a PR that temporarily disables using the system OCaml until beta7 comes out?

If you can make that to work it would be great.

**Pull request merged**
